name: weekly-seed

on:
  schedule:
    - cron: '20 3 * * 0'      # every Sunday 03:20 UTC
  workflow_dispatch:          # run-on-click in Actions tab

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          #  pull repo

      - name: Set up Python
        uses: actions/setup-python@v5      # install Python
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg[binary] python-dotenv

      - name: Run AniList seed
        env:
          SPRING_DATASOURCE_SEED_URL: ${{ secrets.SPRING_DATASOURCE_SEED_URL }}  # secret -> env
        run: python tools/seed/anilist_seed.py
